# Base16 penumbra contrast+ eight dark
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

set -l color00 '#24272B'
set -l color01 '#3E4044'
set -l color02 '#636363'
set -l color03 '#9E9E9E'
set -l color04 '#CECECE'
set -l color05 '#F2E6D4'
set -l color06 '#FFF7ED'
set -l color07 '#FFFDFB'
set -l color08 '#DF7F78'
set -l color09 '#9CA748'
set -l color0A '#CE9042'
set -l color0B '#50B584'
set -l color0C '#00B3C2'
set -l color0D '#61A3E6'
set -l color0E '#A48FE1'
set -l color0F '#D080B6'

set -l FZF_NON_COLOR_OPTS

for arg in (echo $FZF_DEFAULT_OPTS | tr " " "\n")
    if not string match -q -- "--color*" $arg
        set -a FZF_NON_COLOR_OPTS $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$FZF_NON_COLOR_OPTS"\
" --color=bg+:$color01,bg:$color00,spinner:$color0C,hl:$color0D"\
" --color=fg:$color04,header:$color0D,info:$color0A,pointer:$color0C"\
" --color=marker:$color0C,fg+:$color06,prompt:$color0A,hl+:$color0D"
