# Base16 penumbra balanced eight dark
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

set -l color00 '#303338'
set -l color01 '#3E4044'
set -l color02 '#636363'
set -l color03 '#8F8F8F'
set -l color04 '#BEBEBE'
set -l color05 '#F2E6D4'
set -l color06 '#FFF7ED'
set -l color07 '#FFFDFB'
set -l color08 '#CA736C'
set -l color09 '#8D9741'
set -l color0A '#BA823A'
set -l color0B '#47A477'
set -l color0C '#00A2AF'
set -l color0D '#5794D0'
set -l color0E '#9481CC'
set -l color0F '#BC73A4'

set -l FZF_NON_COLOR_OPTS

for arg in (echo $FZF_DEFAULT_OPTS | tr " " "\n")
    if not string match -q -- "--color*" $arg
        set -a FZF_NON_COLOR_OPTS $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$FZF_NON_COLOR_OPTS"\
" --color=bg+:$color01,bg:$color00,spinner:$color0C,hl:$color0D"\
" --color=fg:$color04,header:$color0D,info:$color0A,pointer:$color0C"\
" --color=marker:$color0C,fg+:$color06,prompt:$color0A,hl+:$color0D"
