[defaults]
        repositories = {
                     main = { path = './repo' }
        }

[configurations.base]
        packages = [
		 'zsh',
		 'git',
		 'ssh',
		 'tmux',
	]

[configurations.workstation]
	dependencies = ['base']
	packages = [
		 'x',
		 'emacs',
		 'font',
		 'herbstluftwm',
		 'alacritty',
		 'polybar',
		 'rofi',
		 'base16',
		 'wallpaper',
		 'tools',
		 'eww',
		 'nvim',
		 'hyprland',
	]

[configurations.3d]
	packages = [
		 'openscad',
	]

[configurations.workstation.collections]
	'base16-activations' = {
        	 destination = '~/.base-16/activations.sh',
              	 perm = "0644",
      	}

[configurations.odin]
	dependencies = [
		'workstation',
		'3d',
	]

[configurations.quarktasche]
	dependencies = [
		'workstation',
		'3d',
	]

[configurations.ostara]
	dependencies = [
		     'workstation',
		     '3d',
	]

[configurations.sulu]
	dependencies = ['workstation']

[configurations.mimir]
	packages = [
		     'zsh',
		     'tmux',
	]
