[defaults]
        repositories = {
                     main = { path = './repo' }
        }

        facts = {
              git = {
                  email      = "sebastian@devunit.eu",
                  signingkey = "779EBA5EB9D631B8!"
              }
        }

[configurations.base]
        packages = ['git', 'zsh', 'tmux', 'terminal']

[configurations.computer]
        dependencies = ['base']
        packages = ['rofi', 'emacs', 'gpg', 'x11', 'hlwm', 'termite', 'qutebrowser', 'systemd', 'scripts', 'wallpaper', 'polybar', 'compton', 'alacritty', 'font']

[configurations.loki]
        dependencies = ['computer']
        packages = ['mpd']

[configurations.odin]
        dependencies = ['computer']
        packages = ['mpd']

[configurations.mimir.rakel-net.de]
        dependencies = ['base']

[configurations.ws-rakel-seb]
        dependencies = ['computer']

        facts = {
              git = {
                  email      = "sebastian.rakel@landwehr.it",
                  signingkey = "7ED04C7F09524295F10DA30515725C19DFA82902"
              }
        }
