[defaults]
        repositories = {
                     main = { path = './repo' }
        }

        facts = {
	      base16-themepath = "~/.base16",
              git = {
                  email      = "sebastian@devunit.eu",
                  signingkey = "779EBA5EB9D631B8!"
              }
        }

[configurations.base]
        packages = [
		 'zsh',
	]

[configurations.workstation]
	dependencies = ['base']
	packages = [
		 'herbstluftwm',
		 'alacritty',
		 'polybar',
		 'rofi',
		 'base16',
	]

[configurations.odin]
	dependencies = ['workstation']
