[defaults]
        repositories = {
                     main = { path = './repo' }
        }

[configurations.base]
        packages = [
		 'zsh',
		 'git',
	]

[configurations.workstation]
	dependencies = ['base']
	packages = [
		 'herbstluftwm',
		 'alacritty',
		 'polybar',
		 'rofi',
		 'base16',
	]

[configurations.workstation.collections]
	'base16-activations' = {
        	 destination = '~/.base-16/activations.sh',
              	 perm = "0644",
      	}

[configurations.odin]
	dependencies = ['workstation']

[configurations.ostara]
	dependencies = ['workstation']