alias tmux='tmux -2'
alias g='git'
alias dd='/usr/bin/dd status=progress'
alias nossh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias grep='grep --color'
alias hc='herbstclient'
alias em='emacsclient -n'
alias ddd='dd oflag=direct status=progress'
alias ddf='dd conv=fsynci status=progress'
alias sudo='sudo '
alias yt-audiodownload='youtube-dl --audio-format best --extract-audio '
alias ip='ip -c'
alias ips='ip -br a'
alias dmesg='dmesg -T --color'
alias ls='ls --color'
alias mkvenv='python -m venv venv'
alias usevenv='source venv/bin/activate'
alias n='nvim '

if which lsd >/dev/null; then
    alias ls='lsd '
fi
