# Base16 Cupcake 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)

# Default colors
[colors.primary]
background = '0xfbf1f2'
foreground = '0x8b8198'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfbf1f2'
cursor = '0x8b8198'

# Normal colors
[colors.normal]
black = '0xfbf1f2'
red = '0xD57E85'
green = '0xA3B367'
yellow = '0xDCB16C'
blue = '0x7297B9'
magenta = '0xBB99B4'
cyan = '0x69A9A7'
white = '0x8b8198'

# Bright colors
[colors.bright]
black = '0xbfb9c6'
red = '0xD57E85'
green = '0xA3B367'
yellow = '0xDCB16C'
blue = '0x7297B9'
magenta = '0xBB99B4'
cyan = '0x69A9A7'
white = '0x585062'

[[colors.indexed_colors]]
index = 16
color = "0xEBB790"

[[colors.indexed_colors]]
index = 17
color = "0xBAA58C"

[[colors.indexed_colors]]
index = 18
color = "0xf2f1f4"

[[colors.indexed_colors]]
index = 19
color = "0xd8d5dd"

[[colors.indexed_colors]]
index = 20
color = "0xa59daf"

[[colors.indexed_colors]]
index = 21
color = "0x72677E"
