# Base16 Nord 256 - alacritty color config
# arcticicestudio

# Default colors
[colors.primary]
background = '0x2E3440'
foreground = '0xE5E9F0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2E3440'
cursor = '0xE5E9F0'

# Normal colors
[colors.normal]
black = '0x2E3440'
red = '0xBF616A'
green = '0xA3BE8C'
yellow = '0xEBCB8B'
blue = '0x81A1C1'
magenta = '0xB48EAD'
cyan = '0x88C0D0'
white = '0xE5E9F0'

# Bright colors
[colors.bright]
black = '0x4C566A'
red = '0xBF616A'
green = '0xA3BE8C'
yellow = '0xEBCB8B'
blue = '0x81A1C1'
magenta = '0xB48EAD'
cyan = '0x88C0D0'
white = '0x8FBCBB'

[[colors.indexed_colors]]
index = 16
color = "0xD08770"

[[colors.indexed_colors]]
index = 17
color = "0x5E81AC"

[[colors.indexed_colors]]
index = 18
color = "0x3B4252"

[[colors.indexed_colors]]
index = 19
color = "0x434C5E"

[[colors.indexed_colors]]
index = 20
color = "0xD8DEE9"

[[colors.indexed_colors]]
index = 21
color = "0xECEFF4"
