# Base16 Material Lighter 256 - alacritty color config
# Nate Peterson

# Default colors
[colors.primary]
background = '0xFAFAFA'
foreground = '0x80CBC4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xFAFAFA'
cursor = '0x80CBC4'

# Normal colors
[colors.normal]
black = '0xFAFAFA'
red = '0xFF5370'
green = '0x91B859'
yellow = '0xFFB62C'
blue = '0x6182B8'
magenta = '0x7C4DFF'
cyan = '0x39ADB5'
white = '0x80CBC4'

# Bright colors
[colors.bright]
black = '0xCCD7DA'
red = '0xFF5370'
green = '0x91B859'
yellow = '0xFFB62C'
blue = '0x6182B8'
magenta = '0x7C4DFF'
cyan = '0x39ADB5'
white = '0xFFFFFF'

[[colors.indexed_colors]]
index = 16
color = "0xF76D47"

[[colors.indexed_colors]]
index = 17
color = "0xE53935"

[[colors.indexed_colors]]
index = 18
color = "0xE7EAEC"

[[colors.indexed_colors]]
index = 19
color = "0xCCEAE7"

[[colors.indexed_colors]]
index = 20
color = "0x8796B0"

[[colors.indexed_colors]]
index = 21
color = "0x80CBC4"
