# Base16 Dracula 256 - alacritty color config
# Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)

# Default colors
[colors.primary]
background = '0x282936'
foreground = '0xe9e9f4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x282936'
cursor = '0xe9e9f4'

# Normal colors
[colors.normal]
black = '0x282936'
red = '0xea51b2'
green = '0xebff87'
yellow = '0x00f769'
blue = '0x62d6e8'
magenta = '0xb45bcf'
cyan = '0xa1efe4'
white = '0xe9e9f4'

# Bright colors
[colors.bright]
black = '0x626483'
red = '0xea51b2'
green = '0xebff87'
yellow = '0x00f769'
blue = '0x62d6e8'
magenta = '0xb45bcf'
cyan = '0xa1efe4'
white = '0xf7f7fb'

[[colors.indexed_colors]]
index = 16
color = "0xb45bcf"

[[colors.indexed_colors]]
index = 17
color = "0x00f769"

[[colors.indexed_colors]]
index = 18
color = "0x3a3c4e"

[[colors.indexed_colors]]
index = 19
color = "0x4d4f68"

[[colors.indexed_colors]]
index = 20
color = "0x62d6e8"

[[colors.indexed_colors]]
index = 21
color = "0xf1f2f8"
