export ZSH=~/.zsh
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return
# Load all of the config files in ~/oh-my-zsh that end in .zsh
for config_file ($ZSH/*.zsh) source $config_file

# Load and run compinit
autoload -U compinit
compinit -i

autoload edit-command-line
zle -N edit-command-line

# check dotfiles version
# dotfiles/checkStatus.sh ~/dotfiles/

source ~/.profile

if hash fzf 2>/dev/null; then    
    source /usr/share/fzf/completion.zsh
    source /usr/share/fzf/key-bindings.zsh
fi

PATH="/home/sebastian/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/sebastian/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/sebastian/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/sebastian/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/sebastian/perl5"; export PERL_MM_OPT;

source /home/sebastian/.config/broot/launcher/bash/br
