export ZSH=~/.zsh
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return
# Load all of the config files in ~/oh-my-zsh that end in .zsh
for config_file ($ZSH/*.zsh) source $config_file

# Load and run compinit
autoload -U compinit
compinit -i

autoload edit-command-line
zle -N edit-command-line

# check dotfiles version
# dotfiles/checkStatus.sh ~/dotfiles/

source ~/.profile

if hash fzf 2>/dev/null; then    
    sourcing=('/usr/share/fzf/completion.zsh' '/usr/share/fzf/key-bindings.zsh')
    for source in $sourcing[@]; do
    	if [[ -e "${source}" ]]; then
		source "${source}"
	fi
    done
fi

autoload -U +X bashcompinit && bashcompinit
source $HOME/.zsh/az.completion
