fpath+=($HOME/.zsh/pure)

for config_file in ${ZSH}/*.zsh; do source $config_file; done
if [[ -e "${HOME}/.zsh-private" ]]; then
   for config_file in ${HOME}/.zsh-private/*.zsh; do source $config_file; done
fi