---
template_lists:
  default: https://raw.githubusercontent.com/sebastianrakel/base16-templates-source/patch-1/list.yaml
scheme_lists:
  default: https://raw.githubusercontent.com/chriskempson/base16-schemes-source/master/list.yaml
scheme_dir: '~/.base-16/schemes'
template_dir: '~/.base-16/templates'
output_dir: '~/.dotfiles/repo/base16/themes'
cache_dir: '~/.base-16/cache'
schemes:
  - gruvbox
  - monokai
  - penumbra
  - default
templates:
  - alacritty
  - emacs
  - dunst
  - fzf
  - polybar
  - rofi
  - emacs
