#!/bin/sh
userresources=~/.Xresources
sysresources=/etc/X11/xinit/.Xresources

systemd_user_path="/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"
[ -f "${systemd_user_path}" ] && source "${systemd_user_path}"

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

. "${HOME}/.profile"


if hash xscreensaver 2>/dev/null; then
    xscreensaver --no-splash &
fi

if hash picom 2>/dev/null; then
    picom -b
fi

xprofile_local="${HOME}/.xprofile.local"
[ -f "${xprofile_local}" ] && . "${xprofile_local}"

cd $HOME
