#!/bin/sh
userresources=~/.Xresources
sysresources=/etc/X11/xinit/.Xresources

systemd_user_path="/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"
[ -f "${systemd_user_path}" ] && source "${systemd_user_path}"

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

source "${HOME}/.profile"

xprofile_local="${HOME}/.xprofile.local"
[ -f "${xprofile_local}" ] && source "${xprofile_local}"

cd $HOME
