#!/bin/sh
userresources=~/.Xresources
sysresources=/etc/X11/xinit/.Xresources

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

source "${HOME}/.profile"

xprofile_local="${HOME}/.xprofile.local"
[ -f "${xprofile_local}" ] && source "${xprofile_local}"

cd $HOME
