;; base16-penumbra-contrast+-eight-light-theme.el -- A base16 colorscheme

;;; Commentary:
;; Base16: (https://github.com/tinted-theming/home)

;;; Authors:
;; Scheme: yushyin (generated by base16-penumbra-scheme-gen.pl)
;; Template: Kaleb Elwert <belak@coded.io>

;;; Code:

(require 'base16-theme)

(defvar base16-penumbra-contrast+-eight-light-theme-colors
  '(:base00 "#FFF7ED"
    :base01 "#F2E6D4"
    :base02 "#CECECE"
    :base03 "#9E9E9E"
    :base04 "#636363"
    :base05 "#3E4044"
    :base06 "#24272B"
    :base07 "#181B1F"
    :base08 "#DF7F78"
    :base09 "#9CA748"
    :base0A "#CE9042"
    :base0B "#50B584"
    :base0C "#00B3C2"
    :base0D "#61A3E6"
    :base0E "#A48FE1"
    :base0F "#D080B6")
  "All colors for Base16 penumbra contrast+ eight light are defined here.")

;; Define the theme
(deftheme base16-penumbra-contrast+-eight-light)

;; Add all the faces to the theme
(base16-theme-define 'base16-penumbra-contrast+-eight-light base16-penumbra-contrast+-eight-light-theme-colors)

;; Mark the theme as provided
(provide-theme 'base16-penumbra-contrast+-eight-light)

(provide 'base16-penumbra-contrast+-eight-light-theme)

;;; base16-penumbra-contrast+-eight-light-theme.el ends here
