;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        kill-region
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        keyboard-escape-quit
        upcase-region
        yaml-electric-backspace
        ))
